### ISSUE TITLE
Big file input crash

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#118]
**Describe the bug**
put big file(url list to file/pipe mode), crash

**To Reproduce**
```
hey brother
(수) 오후 4:52
I ran dalfox against a file list of urls and this file is around 1.6gb in size, when I ran I got this error. I ran on a free tier ec2 instance and not on my computer
Parameter Analysis and XSS Scanning tool based on golang
Finder Of XSS and Dal is the Korean pronunciation of moon. 
@hahwul

[*] Using file mode(targets list)
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb43ee4, 0x16)
/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc030000000, 0x8000000, 0x18c99b8)
/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x18aebe0, 0x6800000, 0x42d677, 0x18aebe8)
/usr/local/go/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x18aebe0, 0x3289, 0x0)
/usr/local/go/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x18aebe0, 0x3289, 0x7f8b02de0000, 0x18c99c8, 0x66)
/usr/local/go/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
/usr/local/go/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x18aebe0, 0x3289, 0x460100, 0x18aebe0)
/usr/local/go/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0x6512000, 0x18c0001, 0x7f8aff723040)
/usr/local/go/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
/usr/local/go/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x0)
/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1116

goroutine 1 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc001085828 sp=0xc001085820 pc=0x46a900
runtime.mallocgc(0x6512000, 0xa56820, 0xc00013e201, 0x676175676e616c26)
/usr/local/go/src/runtime/malloc.go:1070 +0x938 fp=0xc0010858c8 sp=0xc001085828 pc=0x40f6d8
runtime.growslice(0xa56820, 0xc023a80000, 0x50da00, 0x50da00, 0x50da01, 0xc023a80000, 0x40ae00, 0x50da00)
/usr/local/go/src/runtime/slice.go:230 +0x1e9 fp=0xc001085930 sp=0xc0010858c8 pc=0x44e349
http://github.com/hahwul/dalfox/cmd.readLines(0x7ffce1c64857, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/admin/go/src/github.com/hahwul/dalfox/cmd/file.go:136 +0x231 fp=0xc001085a48 sp=0xc001085930 pc=0x9ff1b1
http://github.com/hahwul/dalfox/cmd.readLinesOrLiteral(0x7ffce1c64857, 0x26, 0xb48a4d, 0x1d, 0x0, 0x0, 0x0)
/home/admin/go/src/github.com/hahwul/dalfox/cmd/file.go:147 +0xbf fp=0xc001085a90 sp=0xc001085a48 pc=0x9ff3bf
http://github.com/hahwul/dalfox/cmd.glob..func1(0x188a0a0, 0xc00006b450, 0x1, 0x5)
/home/admin/go/src/github.com/hahwul/dalfox/cmd/file.go:67 +0x795 fp=0xc001085d70 sp=0xc001085a90 pc=0xa017f5
http://github.com/spf13/cobra.(*Command).execute(0x188a0a0, 0xc00006b400, 0x5, 0x5, 0x188a0a0, 0xc00006b400)
/home/admin/go/src/github.com/spf13/cobra/command.go:854 +0x2c2 fp=0xc001085e40 sp=0xc001085d70 pc=0x83e6e2
http://github.com/spf13/cobra.(*Command).ExecuteC(0x188a5e0, 0x446eea, 0xf49560, 0xc000000180)
/home/admin/go/src/github.com/spf13/cobra/command.go:958 +0x375 fp=0xc001085f18 sp=0xc001085e40 pc=0x83f415
http://github.com/spf13/cobra.(*Command).Execute(...)
/home/admin/go/src/github.com/spf13/cobra/command.go:895
http://github.com/hahwul/dalfox/cmd.Execute()
/home/admin/go/src/github.com/hahwul/dalfox/cmd/root.go:34 +0x31 fp=0xc001085f78 sp=0xc001085f18 pc=0x9ff831
main.main()
/home/admin/go/src/github.com/hahwul/dalfox/dalfox.go:10 +0x25 fp=0xc001085f88 sp=0xc001085f78 pc=0xa03045
runtime.main()
/usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc001085fe0 sp=0xc001085f88 pc=0x439d29
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc001085fe8 sp=0xc001085fe0 pc=0x46c6e1
```

**Comment by hahwul** [comment]
```
125 // a slice of strings, returning the slice and any error
126 func readLines(filename string) ([]string, error) {
127         f, err := os.Open(filename)
128         if err != nil {
129                 return []string{}, err
130         }
131         defer f.Close()
132
133         lines := make([]string, 0)
           // i think this!


134         sc := bufio.NewScanner(f)
135         for sc.Scan() {
136                 lines = append(lines, sc.Text())
137         }
138
139         return lines, sc.Err()
140 }
```

**Comment by hahwul** [comment]
https://golang.org/pkg/bufio/#MaxScanTokenSize
