### ISSUE TITLE
panic error with `--custom-payload`

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#162]
## Describe the bug
panic error with `--custom-payload`
```
[*] Start XSS Scanning.. with 48 queries 🗡
 ◤  Make 100 workers and allocated 48 queries panic: runtime error: slice bounds out of range [1:0]

goroutine 1397 [running]:
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc00110a03d, 0x0, 0x0, 0x0, 0x0, 0x3e, 0x5, 0xc000fdc54b, 0x3)
	/home/devi/tools/dalfox/pkg/optimization/abstraction.go:138 +0x21b
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc00110a03d, 0x1, 0x0, 0x0, 0x0, 0x3d, 0x0, 0x0, 0x0)
	/home/devi/tools/dalfox/pkg/optimization/abstraction.go:138 +0xe9
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc00110a03c, 0x2, 0x0, 0x0, 0x0, 0x3c, 0x0, 0x0, 0x0)
	/home/devi/tools/dalfox/pkg/optimization/abstraction.go:138 +0xe9
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc00110a03b, 0x3, 0x0, 0x0, 0x0, 0x3b, 0x0, 0x913e79a700000000, 0xc0011a2ff0)
....
```

1.txt (included empty)
```
a
b
c


```

## Environment
 * Dalfox Version: v2.2.6
 * Installed from: hombrew

**Comment by hahwul** [comment]
before
```
$ dalfox url http://testphp.vulnweb.com/listproducts.php\?artist\=123 --custom-payload 1 --only-custom-payload
goroutine 1429 [running]:
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc0017a133d, 0x0, 0x0, 0x0, 0x0, 0x3e, 0x2062655720786974, 0x626172656e6c7556, 0x6353207974696c69)
	/home/devi/tools/dalfox/pkg/optimization/abstraction.go:138 +0x21b
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc0017a133d, 0x1, 0x0, 0x0, 0x0, 0x3d, 0x612064743c090a3e, 0x656c223d6e67696c, 0x3c09090a3e227466)
	/home/devi/tools/dalfox/pkg/optimization/abstraction.go:138 +0xe9
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc0017a133c, 0x2, 0x0, 0x0, 0x0, 0x3c, 0x223d666572682061, 0x6d69616c63736964, 0x3e227068702e7265)
	/home/devi/tools/dalfox/pkg/optimization/abstraction.go:138 +0xe9
github.com/hahwul/dalfox/pkg/optimization.FindIndexesInLine(0xc0017a133b, 0x3, 0x0, 0x0, 0x0, 0x3b, 0x0, 0x60d41d0800000000, 0xc001196ff0)
```

after
```
$ go build
$ ./dalfox url http://testphp.vulnweb.com/listproducts.php\?artist\=123 --custom-payload 1 --only-custom-payload
[I] Found 2 testing point in DOM Mining
[*] Static analysis done ✓
[*] BAV analysis done ✓
[*] Parameter analysis  done ✓
[I] Content-Type is text/html; charset=UTF-8
[I] Reflected cat param => Injected: /inHTML-none(1)  $
    48 line:  	Error: Unknown column 'DalFox' in 'where cl
[I] Reflected artist param => Injected: /inHTML-none(1)  $
    48 line:  	Error: Unknown column '123DalFox' in 'where cl
[*] Generate XSS payload and optimization.Optimization.. 🛠
[*] Type is 'text/html; charset=UTF-8', It does not test except customized payload (custom/blind).
[*] Added your 6 custom xss payload
[*] Start XSS Scanning.. with 18 queries 🗡
[*] Finish :D
```
