### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#198]
```
[*] Starting API Server
[*] Listen 0.0.0.0:6664
{"time":"2021-02-18T22:46:40.609612293+09:00","id":"","remote_ip":"127.0.0.1","host":"localhost:6664","method":"POST","uri":"/scan","status":200,"error":"","latency":260584,"latency_human":"260.584µs","bytes_in":37,"bytes_out":98}
 ⠴  [SA: ✓ SP: ✓ BAV: ✓ ] Waiting for parameter and static analysis 🔍 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x81c771]

goroutine 25 [running]:
github.com/hahwul/dalfox/v2/pkg/scanning.Scan.func2(0xc0000c72d0, 0xc0007342c0, 0x1a, 0xc00073e200, 0xc000010038, 0xc00017e850, 0xc00017e860, 0xc00017e870)
	/home/devi/go/pkg/mod/github.com/hahwul/dalfox/v2@v2.3.1/pkg/scanning/scan.go:139 +0x151
created by github.com/hahwul/dalfox/v2/pkg/scanning.Scan
	/home/devi/go/pkg/mod/github.com/hahwul/dalfox/v2@v2.3.1/pkg/scanning/scan.go:136 +0x845

```

**Comment by hahwul** [comment]
```go
func ScanFromAPI(url string, rqOptions model.Options, options model.Options, sid string) {
	rqOptions.Scan = options.Scan
	scan.Scan(url, rqOptions, sid)
}
```
rqOptions에는 auroraObject가 없음
