### ISSUE TITLE
server misbehaving

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#20]
```
[INF] Loaded 1 target urls
[INF] Target URL: https://asdfa
[INF] start parameter analysis..🔍
[INF] start static analysis..🔍
panic: Get https://asdfa: dial tcp: lookup asdfa on 127.0.0.53:53: server misbehaving

goroutine 6 [running]:
github.com/hahwul/dalfox/core.SendReq(0xbfc4a585, 0xd, 0x8c12d60, 0x0, 0x0, 0x0)
	/home/hahwul/tool/dalfox/core/scan.go:316 +0x6bd
github.com/hahwul/dalfox/core.StaticAnalysis(0xbfc4a585, 0xd, 0x8c12d60, 0x82e3702)
	/home/hahwul/tool/dalfox/core/scan.go:193 +0x41
github.com/hahwul/dalfox/core.Scan.func1(0x8c18540, 0xbfc4a585, 0xd, 0x8c12d60, 0x8c106a0)
	/home/hahwul/tool/dalfox/core/scan.go:38 +0xaa
created by github.com/hahwul/dalfox/core.Scan
	/home/hahwul/tool/dalfox/core/scan.go:35 +0x1d1
```

**Comment by hahwul** [comment]
이것도 같은거같음
[FTL] Fatal error Get http://154.0.0.1: dial tcp 154.0.0.1:80: connect: connection refused
exit status 1
