### ISSUE TITLE
간헐적으로 stacktrace..

### ISSUE THREAD

**Issue by hahwul** [hahwul/dalfox#33]
```
goroutine 28 [running]:
runtime.throw(0x135df4d, 0x15)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72 fp=0xc00081be60 sp=0xc00081be30 pc=0x10338f2
runtime.mapassign_faststr(0x12fa080, 0xc000194000, 0x7ffeefbff7ba, 0xa, 0xc00009b0b0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/map_faststr.go:291 +0x3de fp=0xc00081bec8 sp=0xc00081be60 pc=0x101490e
github.com/hahwul/dalfox/core.ParameterAnalysis.func1.1(0xc0003aa0d0, 0x7ffeefbff781, 0x44, 0x7ffeefbff7ba, 0xa, 0x13538e2, 0x1, 0xc00009b0b0, 0xc0000c6120, 0xc000194000)
	/Users/hahwul/go/src/github.com/hahwul/dalfox/core/scan.go:442 +0x1e0 fp=0xc00081bf90 sp=0xc00081bec8 pc=0x12b8830
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00081bf98 sp=0xc00081bf90 pc=0x10629f1
created by github.com/hahwul/dalfox/core.ParameterAnalysis.func1
	/Users/hahwul/go/src/github.com/hahwul/dalfox/core/scan.go:436 +0x678
```

이유를 찾아보니, go routine간 의 race condition으로 인해 발생하는 문제같음.
결국 공통 변수에 데이터를 쓸 떄 mutex.Lock()후 쓰고, Unlock 해야할듯

**Comment by hahwul** [comment]
```
go run -race dalfox.go -url {target}
=>

WARNING: DATA RACE
Read at 0x00c0003080b0 by goroutine 46:
  runtime.growslice()
      /usr/local/Cellar/go/1.14/libexec/src/runtime/slice.go:76 +0x0
  github.com/hahwul/dalfox/core.ParameterAnalysis.func1()
      /Users/hahwul/HAHWUL/tool/dalfox/core/scan.go:324 +0x31f

Previous write at 0x00c0003080b0 by goroutine 45:
  github.com/hahwul/dalfox/core.ParameterAnalysis.func1()
      /Users/hahwul/HAHWUL/tool/dalfox/core/scan.go:324 +0x203

Goroutine 46 (running) created at:
  github.com/hahwul/dalfox/core.ParameterAnalysis()
      /Users/hahwul/HAHWUL/tool/dalfox/core/scan.go:319 +0xbe4
  github.com/hahwul/dalfox/core.Scan.func2()
      /Users/hahwul/HAHWUL/tool/dalfox/core/scan.go:66 +0xdd

Goroutine 45 (finished) created at:
  github.com/hahwul/dalfox/core.ParameterAnalysis()
      /Users/hahwul/HAHWUL/tool/dalfox/core/scan.go:319 +0xbe4
  github.com/hahwul/dalfox/core.Scan.func2()
      /Users/hahwul/HAHWUL/tool/dalfox/core/scan.go:66 +0xdd
....
```

**Comment by hahwul** [comment]
이후 `go run -race dalfox.go -url` 시 발생하지 않음
