### ISSUE TITLE
dalfox has suddenly stopped working

### ISSUE THREAD

**Issue by AnubisTwine** [hahwul/dalfox#430]
this is the output i am now getting 

 ⠸  [SA: ✓ PA: ✓ BAV: ✓ ] Waiting for analysis 🔍panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x5f0df4]

goroutine 26 [running]:
net/url.(*URL).Query(0xc000f79200)
	/usr/local/go/src/net/url/url.go:1130 +0x14
github.com/hahwul/dalfox/v2/pkg/scanning.ParameterAnalysis.func6(0xc00000e028, 0xc00056a000)
	/Users/ichei/Projects/release/dalfox/pkg/scanning/parameterAnlaysis.go:193 +0xaa
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000f404b0, 0xc0000e5318)
	/Users/ichei/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:10 +0x46
github.com/hahwul/dalfox/v2/pkg/scanning.ParameterAnalysis({_, _}, {{0x1ba2cf8, 0x0, 0x0}, {0x0, 0x0}, {0x1ba2cf8, 0x0, 0x0}, ...}, ...)
	/Users/ichei/Projects/release/dalfox/pkg/scanning/parameterAnlaysis.go:189 +0xf05
github.com/hahwul/dalfox/v2/pkg/scanning.Scan.func3()
	/Users/ichei/Projects/release/dalfox/pkg/scanning/scan.go:151 +0xf8
created by github.com/hahwul/dalfox/v2/pkg/scanning.Scan
	/Users/ichei/Projects/release/dalfox/pkg/scanning/scan.go:149 +0x1195

**Comment by hahwul** [comment]
This issue has been addressed in v3 (Rust rewrite). Closing as fixed in v3. If you still see the problem or need re-verification, please reopen the issue. Thank you for reporting!
